from rest_framework import serializers

from django.contrib.auth.models import Group, User
from .models import Event, Listing, Company



COMPANY_GROUP_NAME = 'company'

#Translates between DB-objekt and JSON

class EventSerializer(serializers.ModelSerializer):
    image = serializers.ImageField(use_url=True, required=False, allow_null=True)
    host_company = serializers.SerializerMethodField()

    class Meta:
        model = Event
        fields = '__all__'

    def get_host_company(self, obj):
        creator = getattr(obj, "created_by", None)
        if creator is None:
            return ""

        full_name = creator.get_full_name().strip()
        if full_name:
            return full_name

        if creator.first_name:
            return creator.first_name

        if creator.username:
            return creator.username

        return creator.email or ""


class ListingSerializer(serializers.ModelSerializer):
    image = serializers.ImageField(use_url=True, required=False, allow_null=True)
    location = serializers.SerializerMethodField()

    class Meta:
        model = Listing
        fields = '__all__'

    def get_location(self, obj):
        return obj.city

    def to_internal_value(self, data):
        mutable_data = data.copy()

        if mutable_data.get('location') and not mutable_data.get('city'):
            mutable_data['city'] = mutable_data['location']

        return super().to_internal_value(mutable_data)


class CompanySerializer(serializers.ModelSerializer):
    image = serializers.ImageField(use_url=True)

    class Meta:
        model = Company
        fields = '__all__'


# Generated by ChatGPT on 2026-02-15 14:30:00 UTC by Sindre Navelsaker
# Start

class UserPublicSerializer(serializers.ModelSerializer):
    fullName = serializers.SerializerMethodField()
    role = serializers.SerializerMethodField()

    class Meta:
        model = User
        fields = ['id', 'email', 'fullName', 'role']

    def get_fullName(self, obj):
        full_name = obj.get_full_name().strip()
        if full_name:
            return full_name
        return obj.first_name or obj.username

    def get_role(self, obj):
        if obj.is_staff or obj.is_superuser:
            return 'admin'
        if obj.groups.filter(name=COMPANY_GROUP_NAME).exists():
            return 'company'
        return 'student'


class RegisterSerializer(serializers.Serializer):
    email = serializers.EmailField()
    fullName = serializers.CharField(max_length=150)
    password = serializers.CharField(min_length=6, write_only=True)
    role = serializers.ChoiceField(choices=['student', 'company'], default='student')

    def validate_email(self, value):
        email = value.strip().lower()
        if User.objects.filter(email__iexact=email).exists():
            raise serializers.ValidationError('A user with this email already exists.')
        if User.objects.filter(username__iexact=email).exists():
            raise serializers.ValidationError('A user with this email already exists.')
        return email

    def create(self, validated_data):
        role = validated_data.get('role', 'student')
        user = User.objects.create_user(
            username=validated_data['email'],
            email=validated_data['email'],
            first_name=validated_data['fullName'].strip(),
            password=validated_data['password'],
        )

        if role == 'company':
            company_group, _ = Group.objects.get_or_create(name=COMPANY_GROUP_NAME)
            user.groups.add(company_group)

        return user


class LoginSerializer(serializers.Serializer):
    email = serializers.CharField()
    password = serializers.CharField(write_only=True)

    def validate(self, attrs):
        email_or_username = attrs['email'].strip()
        password = attrs['password']

        user = User.objects.filter(email__iexact=email_or_username).first()
        if user is None:
            user = User.objects.filter(username__iexact=email_or_username).first()

        if user is None or not user.check_password(password):
            raise serializers.ValidationError('Invalid email or password.')

        if not user.is_active:
            raise serializers.ValidationError('This account is inactive.')

        attrs['user'] = user
        return attrs
    
# End
