from django.contrib.auth.models import User
from rest_framework import generics
from rest_framework import status
from rest_framework.exceptions import PermissionDenied, ValidationError
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Event, Listing, Company, Registration
from .serializers import (
    COMPANY_GROUP_NAME,
    EventSerializer,
    ListingSerializer,
    CompanySerializer,
    UserPublicSerializer,
    RegisterSerializer,
    LoginSerializer,
)

# Generated by ChatGPT by Sindre Navelsaker


class CompanyContentAccessMixin:
    def get_company_user(self, user_id):
        if not user_id:
            raise ValidationError({'created_by': ['This field is required.']})

        try:
            user = User.objects.get(pk=user_id)
        except User.DoesNotExist as exc:
            raise ValidationError({'created_by': ['User does not exist.']}) from exc

        if not user.groups.filter(name=COMPANY_GROUP_NAME).exists():
            raise PermissionDenied('Only company users can create or edit content.')

        return user

    def perform_create(self, serializer):
        company_user = self.get_company_user(self.request.data.get('created_by'))
        serializer.save(created_by=company_user)

    def perform_update(self, serializer):
        instance = self.get_object()
        creator_id = self.request.data.get('created_by', instance.created_by_id)
        company_user = self.get_company_user(creator_id)

        if company_user.id != instance.created_by_id:
            raise PermissionDenied('Content can only be edited by the company that created it.')

        serializer.save(created_by=company_user)


class EventList(CompanyContentAccessMixin, generics.ListCreateAPIView):
    queryset = Event.objects.all()
    serializer_class = EventSerializer
    permission_classes = [AllowAny]

    def get_queryset(self):
        queryset = Event.objects.all()
        created_by = self.request.query_params.get('created_by')

        if created_by:
            queryset = queryset.filter(created_by=created_by)

        return queryset


class EventDetail(CompanyContentAccessMixin, generics.RetrieveUpdateAPIView):
    queryset = Event.objects.all()
    serializer_class = EventSerializer
    permission_classes = [AllowAny]


class ListingList(CompanyContentAccessMixin, generics.ListCreateAPIView):
    queryset = Listing.objects.all()
    serializer_class = ListingSerializer
    permission_classes = [AllowAny]

    def get_queryset(self):
        queryset = Listing.objects.all()
        created_by = self.request.query_params.get('created_by')

        if created_by:
            queryset = queryset.filter(created_by=created_by)

        return queryset


class ListingDetail(CompanyContentAccessMixin, generics.RetrieveUpdateAPIView):
    queryset = Listing.objects.all()
    serializer_class = ListingSerializer
    permission_classes = [AllowAny]


class CompanyList(generics.ListAPIView):
    queryset = Company.objects.all().order_by("name")
    serializer_class = CompanySerializer


class CompanyDetail(generics.RetrieveAPIView):
    queryset = Company.objects.all()
    serializer_class = CompanySerializer


class EventRegistrationView(APIView):
    permission_classes = [AllowAny]

    def _get_user(self, request):
        user_id = request.data.get('user_id') or request.query_params.get('user_id')
        if not user_id:
            raise ValidationError({'user_id': ['This field is required.']})

        try:
            return User.objects.get(pk=user_id)
        except User.DoesNotExist as exc:
            raise ValidationError({'user_id': ['User does not exist.']}) from exc

    def get(self, request, pk):
        event = generics.get_object_or_404(Event, pk=pk)
        user = self._get_user(request)
        is_registered = Registration.objects.filter(user=user, event=event).exists()
        registrations_count = Registration.objects.filter(event=event).count()

        return Response(
            {
                'is_registered': is_registered,
                'registrations_count': registrations_count,
            },
            status=status.HTTP_200_OK,
        )

    def post(self, request, pk):
        event = generics.get_object_or_404(Event, pk=pk)
        user = self._get_user(request)
        if user.groups.filter(name=COMPANY_GROUP_NAME).exists():
            raise PermissionDenied('Company users cannot register for events.')

        _, created = Registration.objects.get_or_create(user=user, event=event)
        if not created:
            return Response(
                {'detail': 'User is already registered for this event.'},
                status=status.HTTP_400_BAD_REQUEST,
            )

        return Response({'detail': 'Registered successfully.'}, status=status.HTTP_201_CREATED)

    def delete(self, request, pk):
        event = generics.get_object_or_404(Event, pk=pk)
        user = self._get_user(request)
        deleted_count, _ = Registration.objects.filter(user=user, event=event).delete()

        if deleted_count == 0:
            return Response(
                {'detail': 'Registration not found.'},
                status=status.HTTP_404_NOT_FOUND,
            )

        return Response({'detail': 'Registration removed.'}, status=status.HTTP_200_OK)


def build_event_participants(event):
    registrations = Registration.objects.filter(event=event).select_related('user')
    participants = [
        {
            'id': registration.user.id,
            'email': registration.user.email,
            'fullName': (
                registration.user.get_full_name().strip()
                or registration.user.first_name
                or registration.user.username
            ),
        }
        for registration in registrations
    ]

    return {
        'registrations_count': len(participants),
        'participants': participants,
    }


class EventParticipantsView(APIView):
    permission_classes = [AllowAny]

    def get(self, request, pk):
        event = generics.get_object_or_404(Event, pk=pk)
        return Response(build_event_participants(event), status=status.HTTP_200_OK)


class EventRegistrationsForCompanyView(APIView):
    permission_classes = [AllowAny]

    def _get_company_user(self, request):
        company_user_id = request.query_params.get('company_user_id')
        if not company_user_id:
            raise ValidationError({'company_user_id': ['This field is required.']})

        try:
            company_user = User.objects.get(pk=company_user_id)
        except User.DoesNotExist as exc:
            raise ValidationError({'company_user_id': ['User does not exist.']}) from exc

        if not company_user.groups.filter(name=COMPANY_GROUP_NAME).exists():
            raise PermissionDenied('Only company users can view event registrations.')

        return company_user

    def get(self, request, pk):
        company_user = self._get_company_user(request)
        event = generics.get_object_or_404(Event, pk=pk)

        if event.created_by_id != company_user.id:
            raise PermissionDenied('You can only view registrations for your own events.')

        return Response(build_event_participants(event), status=status.HTTP_200_OK)



class RegisterView(APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        serializer = RegisterSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        return Response(UserPublicSerializer(user).data, status=status.HTTP_201_CREATED)


class LoginView(APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        serializer = LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        return Response(UserPublicSerializer(user).data, status=status.HTTP_200_OK)
    

