from django.contrib.auth.models import User
from rest_framework import generics
from rest_framework import status
from rest_framework.exceptions import PermissionDenied, ValidationError
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Event, Listing
from .serializers import (
    COMPANY_GROUP_NAME,
    EventSerializer,
    ListingSerializer,
    UserPublicSerializer,
    RegisterSerializer,
    LoginSerializer,
)

# API/Controller-layer


class CompanyContentAccessMixin:
    def get_company_user(self, user_id):
        if not user_id:
            raise ValidationError({'created_by': ['This field is required.']})

        try:
            user = User.objects.get(pk=user_id)
        except User.DoesNotExist as exc:
            raise ValidationError({'created_by': ['User does not exist.']}) from exc

        if not user.groups.filter(name=COMPANY_GROUP_NAME).exists():
            raise PermissionDenied('Only company users can create or edit content.')

        return user

    def perform_create(self, serializer):
        company_user = self.get_company_user(self.request.data.get('created_by'))
        serializer.save(created_by=company_user)

    def perform_update(self, serializer):
        instance = self.get_object()
        creator_id = self.request.data.get('created_by', instance.created_by_id)
        company_user = self.get_company_user(creator_id)

        if company_user.id != instance.created_by_id:
            raise PermissionDenied('Content can only be edited by the company that created it.')

        serializer.save(created_by=company_user)


class EventList(CompanyContentAccessMixin, generics.ListCreateAPIView):
    queryset = Event.objects.all()
    serializer_class = EventSerializer
    permission_classes = [AllowAny]

    def get_queryset(self):
        queryset = Event.objects.all()
        created_by = self.request.query_params.get('created_by')

        if created_by:
            queryset = queryset.filter(created_by=created_by)

        return queryset


class EventDetail(CompanyContentAccessMixin, generics.RetrieveUpdateAPIView):
    queryset = Event.objects.all()
    serializer_class = EventSerializer
    permission_classes = [AllowAny]


class ListingList(CompanyContentAccessMixin, generics.ListCreateAPIView):
    queryset = Listing.objects.all()
    serializer_class = ListingSerializer
    permission_classes = [AllowAny]

    def get_queryset(self):
        queryset = Listing.objects.all()
        created_by = self.request.query_params.get('created_by')

        if created_by:
            queryset = queryset.filter(created_by=created_by)

        return queryset


class ListingDetail(CompanyContentAccessMixin, generics.RetrieveUpdateAPIView):
    queryset = Listing.objects.all()
    serializer_class = ListingSerializer
    permission_classes = [AllowAny]

# Generated by ChatGPT on 2026-02-15 14:30:00 UTC by Sindre Navelsaker
# Start

class RegisterView(APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        serializer = RegisterSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        return Response(UserPublicSerializer(user).data, status=status.HTTP_201_CREATED)


class LoginView(APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        serializer = LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        return Response(UserPublicSerializer(user).data, status=status.HTTP_200_OK)
    
# End
