import random
from pathlib import Path
from django.core.management.base import BaseCommand
from django.core.files import File
from django.contrib.auth.models import Group, User
from django.utils.text import slugify
from faker import Faker
from events.models import Event, Listing, Company

# Initialiser Faker
fake = Faker(['no_NO'])


# Generated by Gemini by Henrik C Kran

class Command(BaseCommand):
    help = 'Fyller databasen med DETERMINISTISKE testdata (likt hver gang)'

    @staticmethod
    def _company_token(company_name):
        token = slugify(company_name).replace('-', '')
        return token or 'company'

    @staticmethod
    def _student_credentials(full_name):
        first_name, last_name = full_name.split(" ", 1)
        first_lower = first_name.strip().lower()
        last_lower = last_name.strip().lower()
        email = f"{first_lower}@{last_lower}.no"
        password = f"test{first_lower}123"
        return first_name.strip(), last_name.strip(), email, password

    @staticmethod
    def _create_or_update_student(full_name):
        first_name, last_name, email, password = Command._student_credentials(full_name)

        student, created = User.objects.get_or_create(
            username=email,
            defaults={
                "email": email,
                "first_name": first_name,
                "last_name": last_name,
                "is_active": True,
            },
        )

        updates = []
        if not created:
            if student.email != email:
                student.email = email
                updates.append("email")
            if student.first_name != first_name:
                student.first_name = first_name
                updates.append("first_name")
            if student.last_name != last_name:
                student.last_name = last_name
                updates.append("last_name")
            if not student.is_active:
                student.is_active = True
                updates.append("is_active")

        student.set_password(password)
        updates.append("password")
        student.save(update_fields=updates)
        return student

    def handle(self, *args, **kwargs):
        # --- SEEDING ---
        # Ved å sette dette tallet, vil random.choice og fake.name() 
        # alltid returnere det samme resultatet hver gang scriptet kjøres.
        SEED = 42
        random.seed(SEED)
        Faker.seed(SEED)
        
        self.stdout.write("Sletter gammel data...")
        Event.objects.all().delete()
        Listing.objects.all().delete()
        Company.objects.all().delete()

        # Konfigurasjon
        categories = ['Sosialt', 'Kurs', 'Bedriftspresentasjon', 'Idrett', 'Konsert']
        cities = ['Trondheim', 'Oslo', 'Bergen', 'Stavanger', 'Tromsø' ]
        job_types = ['Fulltid', 'Deltid', 'Internship', 'Sommerjobb']
        company_names = ['BDO', 'Equinor', 'Itera', 'Sopra Steria', 'Netlight', 'Kongsberg']
        listing_logo_by_company = {
            "BDO": "bdo.png",
            "Equinor": "equinor.png",
            "Itera": "Itera.png",
            "Sopra Steria": "sopra_steria.png",
            "Netlight": "netlight.png",
            "Kongsberg": "kongsberg.png",
        }
        listings_logo_dir = Path(__file__).resolve().parents[4] / "frontend" / "src" / "assets" / "listings"
        company_group, _ = Group.objects.get_or_create(name='company')

        # 2. Generer firmaer
        self.stdout.write("Genererer firmaer...")
        companies_with_users = []
        for name in company_names:
            token = self._company_token(name)
            username = token
            email = f'{token}@{token}.com'
            password = f'test{token}123'

            company_user, created = User.objects.get_or_create(
                username=username,
                defaults={
                    'email': email,
                    'first_name': name,
                    'is_active': True,
                },
            )
            if created:
                company_user.set_password(password)
                company_user.save(update_fields=['password'])
            else:
                updates = []
                if company_user.email != email:
                    company_user.email = email
                    updates.append('email')
                if company_user.first_name != name:
                    company_user.first_name = name
                    updates.append('first_name')
                if not company_user.is_active:
                    company_user.is_active = True
                    updates.append('is_active')
                company_user.set_password(password)
                updates.append('password')
                company_user.save(update_fields=updates)

            company_user.groups.add(company_group)

            company = Company.objects.create(
                name=name,
                industry=fake.bs(),
                description=fake.paragraph(nb_sentences=3),
                created_by=company_user
            )
            companies_with_users.append((company, company_user))

        # 3. Generer arrangementer
        self.stdout.write("Genererer 25 arrangementer...")
        for _ in range(25):
            company, company_user = random.choice(companies_with_users)
            Event.objects.create(
                title=fake.catch_phrase(),
                category=random.choice(categories),
                # Vi bruker en fast start_date for at datoene skal bli like
                date=fake.date_between(start_date='today', end_date='+90d'),
                description=fake.paragraph(nb_sentences=5),
                places=random.choice(['Ballsalen', 'Edgar', 'Klubben', 'Strossa']),
                capacity=random.randint(20, 500),
                created_by=company_user
            )

        # 4. Generer jobbannonser
        self.stdout.write("Genererer 20 jobbannonser...")
        for _ in range(20):
            company, company_user = random.choice(companies_with_users)
            listing = Listing.objects.create(
                title=fake.job(),
                company=company.name,
                description=fake.text(max_nb_chars=1000),
                employment_type=random.choice(job_types),
                city=random.choice(cities),
                created_by=company_user
            )
            logo_filename = listing_logo_by_company.get(company.name)
            if logo_filename:
                logo_path = listings_logo_dir / logo_filename
                if logo_path.exists():
                    with open(logo_path, "rb") as logo_file:
                        listing.image.save(logo_filename, File(logo_file), save=True)
                else:
                    self.stdout.write(self.style.WARNING(
                        f"Fant ikke logo for {company.name}: {logo_path}"
                    ))

        # 5. Generer teststudenter
        self.stdout.write("Genererer 10 studenter...")
        fixed_student_names = [
            "Sindre Navelsaker",
            "Amohan Kannan",
            "Henrik Kran",
            "Maria Fløstrand",
            "Vilde Tveiten",
        ]
        random_student_names = []
        while len(random_student_names) < 5:
            random_name = f"{fake.first_name()} {fake.last_name()}"
            if random_name in fixed_student_names or random_name in random_student_names:
                continue
            random_student_names.append(random_name)

        all_student_names = fixed_student_names + random_student_names
        created_students = [self._create_or_update_student(full_name) for full_name in all_student_names]

        self.stdout.write(self.style.SUCCESS(
            f'Ferdig! Generert {Company.objects.count()} firmaer, '
            f'{Event.objects.count()} events, {Listing.objects.count()} annonser '
            f'og {len(created_students)} studenter. '
            f'Dataene er identiske med forrige kjøring pga. SEED {SEED}.'
        ))
