# Generated by Django 5.2.11 on 2026-03-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seed_default_company_user'),
        ('events', '0004_company_image'),
    ]

    operations = [
    ]
