# Generated by ChatGPT by Vilde Tveiten

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seed_default_company_user'),
        ('events', '0004_company_image'),
    ]

    operations = [
    ]
