const BASE_URL = "http://127.0.0.1:8000/api";

async function requestJson(path) {
  const response = await fetch(`${BASE_URL}${path}`);

  if (!response.ok) {
    throw new Error(`Request failed: ${response.status}`);
  }

  return response.json();
}

async function parseResponse(response) {
  const payload = await response.json().catch(() => ({}));

  if (!response.ok) {
    const firstError = Object.values(payload).find((value) => Array.isArray(value));
    const message =
      payload?.detail ||
      payload?.non_field_errors?.[0] ||
      payload?.email?.[0] ||
      firstError?.[0] ||
      "Request failed";
    throw new Error(message);
  }

  return payload;
}

// Generated by ChatGPT on 2026-02-15 14:30:00 UTC by Sindre Navelsaker
// Start

async function requestJsonWithBody(path, body) {
  const response = await fetch(`${BASE_URL}${path}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  return parseResponse(response);
}

async function requestJsonWithMethod(path, method) {
  const response = await fetch(`${BASE_URL}${path}`, { method });
  return parseResponse(response);
}

async function requestMultipart(path, formData, method = "POST") {
  const response = await fetch(`${BASE_URL}${path}`, {
    method,
    body: formData,
  });

  return parseResponse(response);
}

function toFormData(data) {
  const formData = new FormData();

  Object.entries(data).forEach(([key, value]) => {
    if (value === undefined || value === null || value === "") {
      return;
    }

    formData.append(key, value);
  });

  return formData;
}

// End

export async function fetchEvents() {
  return requestJson("/events/");
}

export async function fetchEventsByCreator(userId) {
  return requestJson(`/events/?created_by=${userId}`);
}

export async function fetchEventById(id) {
  return requestJson(`/events/${id}/`);
}

export async function fetchAds() {
  return requestJson("/listing/");
}

export async function fetchAdsByCreator(userId) {
  return requestJson(`/ads/?created_by=${userId}`);
}

export async function fetchListingById(id) {
  return requestJson(`/listing/${id}/`);
}

export async function fetchCompanies() {
  return requestJson("/companies/");
}

export async function fetchCompanyById(id) {
  return requestJson(`/companies/${id}/`);
}

// Generated by ChatGPT on 2026-02-15 14:30:00 UTC by Sindre Navelsaker
// Start

export async function registerUser(userData) {
  return requestJsonWithBody("/auth/register/", userData);
}

export async function loginUser(credentials) {
  return requestJsonWithBody("/auth/login/", credentials);
}

export async function createEvent(eventData) {
  return requestMultipart("/events/", toFormData(eventData));
}

export async function updateEvent(id, eventData) {
  return requestMultipart(`/events/${id}/`, toFormData(eventData), "PATCH");
}

export async function createListing(listingData) {
  return requestMultipart("/ads/", toFormData(listingData));
}

export async function updateListing(id, listingData) {
  return requestMultipart(`/ads/${id}/`, toFormData(listingData), "PATCH");
}

export async function fetchEventRegistrationStatus(eventId, userId) {
  return requestJson(`/events/${eventId}/register/?user_id=${userId}`);
}

export async function registerForEvent(eventId, userId) {
  return requestJsonWithBody(`/events/${eventId}/register/`, { user_id: userId });
}

export async function unregisterFromEvent(eventId, userId) {
  const query = `/events/${eventId}/register/?user_id=${userId}`;
  return requestJsonWithMethod(query, "DELETE");
}

export async function fetchEventRegistrationsForCompany(eventId, companyUserId) {
  const query = `/events/${eventId}/registrations/?company_user_id=${companyUserId}`;
  return requestJson(query);
}
// End
