const BASE_URL = "http://127.0.0.1:8000/api";

async function requestJson(path) {
  const response = await fetch(`${BASE_URL}${path}`);

  if (!response.ok) {
    throw new Error(`Request failed: ${response.status}`);
  }

  return response.json();
}

// Generated by ChatGPT on 2026-02-15 14:30:00 UTC by Sindre Navelsaker
// Start

async function requestJsonWithBody(path, body) {
  const response = await fetch(`${BASE_URL}${path}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  const payload = await response.json().catch(() => ({}));

  if (!response.ok) {
    const message =
      payload?.detail ||
      payload?.non_field_errors?.[0] ||
      payload?.email?.[0] ||
      "Request failed";
    throw new Error(message);
  }

  return payload;
}

// End

export async function fetchEvents() {
  return requestJson("/events/");
}

export async function fetchEventById(id) {
  return requestJson(`/events/${id}/`);
}

export async function fetchAds() {
  return requestJson("/listing/");
}

export async function fetchListingById(id) {
  return requestJson(`/listing/${id}/`);
}

// Generated by ChatGPT on 2026-02-15 14:30:00 UTC by Sindre Navelsaker
// Start

export async function registerUser(userData) {
  return requestJsonWithBody("/auth/register/", userData);
}

export async function loginUser(credentials) {
  return requestJsonWithBody("/auth/login/", credentials);
}
// End
