from rest_framework.test import APITestCase
from django.urls import reverse
from django.contrib.auth.models import User
from events.models import Event

# Parts of the code was generated by ChatGPT by Sindre Navelsaker

class ExploreEventsTest(APITestCase):
    def setUp(self):

        self.user = User.objects.create_user(username="testuser", password="testpass")
        
        self.event1 = Event.objects.create(
            title="Event 1",
            description="Description for Event 1",
            date="2024-07-01",
            places = "Place 1",
            created_by=self.user
        )

        self.event2 = Event.objects.create(
            title = "Event 2",
            description = "Description for Event 2",
            date = "2024-08-01",
            places = "Place 2",
            created_by=self.user
            
            
        )

    def test_explore_events_returns_events(self):
        
        response = self.client.get("/api/events/", format="json")


        self.assertEqual(response.status_code, 200)
        self.assertEqual(len(response.data), 2)

        
        titles = [event["title"] for event in response.data]
        self.assertIn(self.event1.title, titles)
        self.assertIn(self.event2.title, titles)   

    
    
    def test_explore_events_returns_empty_list_when_no_events(self):
        Event.objects.all().delete()  

        response = self.client.get("/api/events/", format="json")

        self.assertEqual(response.status_code, 200)
        self.assertEqual(len(response.data), 0)



    
    def test_event_details_returns_correct_event(self):
        response = self.client.get(f"/api/events/{self.event1.id}/", format="json")

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.data["title"], self.event1.title)
        self.assertEqual(response.data["description"], self.event1.description)
        self.assertEqual(response.data["date"], str(self.event1.date))
        self.assertEqual(response.data["places"], self.event1.places)


    def test_event_details_returns_404_for_nonexistent_event(self):
        response = self.client.get("/api/events/999/", format="json")

        self.assertEqual(response.status_code, 404)
        
