from rest_framework.test import APITestCase
from django.contrib.auth.models import User
from events.models import Event, Registration
from events.serializers import (
    UserPublicSerializer,
    RegisterSerializer,
    LoginSerializer
)

# Parts of the code was generated by ChatGPT by Sindre Navelsaker

class TestSerializers(APITestCase):

    def test_user_public_serializer_fullname_and_role_student(self):
        user = User.objects.create_user(username="testuser", 
                                        email="test@example.com", 
                                        first_name="Test", 
                                        last_name="User", 
                                        password="testpass")
        

        serializer = UserPublicSerializer(user)
        data = serializer.data

        self.assertEqual(data["fullName"], "Test User")
        self.assertEqual(data["role"], "student")
        self.assertEqual(data["totalDots"], 0)
        self.assertIn("email", data)


    def test_user_public_serializer_fullname_and_role_admin(self):
        user = User.objects.create_superuser(username="adminuser", 
                                            email="admin@example.com",
                                            password="adminpass")
        
        serializer = UserPublicSerializer(user)
        data = serializer.data

        self.assertEqual(data["role"], "admin")
        self.assertEqual(data["totalDots"], 0)

    def test_user_public_serializer_total_dots_sum(self):
        company_user = User.objects.create_user(
            username="company@example.com",
            email="company@example.com",
            password="password123",
        )
        user = User.objects.create_user(
            username="student@example.com",
            email="student@example.com",
            password="password123",
        )
        event_one = Event.objects.create(
            title="Event one",
            category="Sosialt",
            date="2026-06-01",
            description="desc",
            places="Oslo",
            created_by=company_user,
        )
        event_two = Event.objects.create(
            title="Event two",
            category="Sosialt",
            date="2026-06-02",
            description="desc",
            places="Oslo",
            created_by=company_user,
        )
        Registration.objects.create(user=user, event=event_one, dots=1)
        Registration.objects.create(user=user, event=event_two, dots=2)

        serializer = UserPublicSerializer(user)
        self.assertEqual(serializer.data["totalDots"], 3)


    def test_register_serializer_rejects_duplicate_email(self):
        User.objects.create_user(
            username="duplicate@test.com",
            email="duplicate@test.com",
            password="password123"
        )

        data = {
            "email": "duplicate@test.com",
            "fullName": "Another User",
            "password": "password123"
        }

        serializer = RegisterSerializer(data=data)

        self.assertFalse(serializer.is_valid())
        self.assertIn("email", serializer.errors)
   

    def test_login_serializer_success(self):

        user = User.objects.create_user(
            username="loginuser",
            email="loginuser@example.com",
            password="loginpass"
        )

        data = {
            "email": "loginuser@example.com",
            "password": "loginpass"
        }

        serializer = LoginSerializer(data=data)

        self.assertTrue(serializer.is_valid())
        self.assertEqual(serializer.validated_data["user"], user)


    def test_login_serializer_invalid_password(self):
        User.objects.create_user(
            username="wrongloginuser2",
            email="wrongloginuser2@example.com",
            password="correctpassword"
        )

        data = {
            "email": "wrongloginuser2@example.com",
            "password": "incorrectpassword"
        }

        serializer = LoginSerializer(data=data)

        self.assertFalse(serializer.is_valid())
        
